#ifndef BACKGROUNDAPPLIER_H
#define BACKGROUNDAPPLIER_H

#include "ColorStop.h"
#include <QWidget>

namespace Ui {
class BackgroundApplier;
}


class BackgroundApplier : public QWidget
{
    Q_OBJECT

public:
    explicit BackgroundApplier(QWidget *parent = nullptr);
    ~BackgroundApplier();

    void SetSize(int,int);

    QImage GetImage();

signals:
    void BackgroundApplied(QImage) const;

private slots:
    void on_presets_comboBox_currentIndexChanged(int);
    void on_gradient_type_currentIndexChanged(int);
    void on_spread_comboBox_currentIndexChanged(int);
    void on_rotate_valueChanged(int);
    void on_add_color_stop_button_clicked();
    void on_choose_image_button_clicked();

private:
    Ui::BackgroundApplier *ui;
    int w;
    int h;

    QImage image;
    QGradient::Preset preset;

    std::vector<ColorStop*> color_stops;

    void ApplyPreset();
    void ApplyCustom();
    void OpenFileDialog();
    void AddColorStop(ColorStop*);

    QBrush ApplyLinearGradient(QGradientStops, QGradient::Spread);
    QBrush ApplyRadialGradient(QGradientStops, QGradient::Spread);
    QBrush ApplyConicalGradient(QGradientStops, QGradient::Spread);

    QPointF EdgeOfView(int);

    inline static const QStringList custom_names = {
        "Linear", "Radial", "Conical"
    };

    inline static const QStringList spread_names = {
        "Pad", "Repeat", "Reflect"
    };

    inline static const std::vector<QGradient::Spread> spreads = {
        QGradient::PadSpread,
        QGradient::RepeatSpread,
        QGradient::ReflectSpread
    };

    inline static const QStringList presets_names = {
        "AboveTheSky",
        "AfricanField",
        "AlchemistLab",
        "AmourAmour",
        "AmyCrisp",
        "AngelCare",
        "AquaGuidance",
        "AquaSplash",
        "AwesomePine",
        "BigMango",
        "BlackSea",
        "Blessing",
        "BurningSpring",
        "CheerfulCaramel",
        "ChildCare",
        "CleanMirror",
        "CloudyApple",
        "CloudyKnoxville",
        "CochitiLake",
        "ColdEvening",
        "ColorfulPeach",
        "ConfidentCloud",
        "CrystalRiver",
        "Crystalline",
        "DeepBlue",
        "DeepRelief",
        "DenseWater",
        "DesertHump",
        "DirtyBeauty",
        "DustyGrass",
        "EternalConstance",
        "EverlastingSky",
        "FabledSunset",
        "FarawayRiver",
        "FebruaryInk",
        "FlyHigh",
        "FlyingLemon",
        "ForestInei",
        "FreshMilk",
        "FreshOasis",
        "FrozenBerry",
        "FrozenDreams",
        "FrozenHeat",
        "FruitBlend",
        "GagarinView",
        "GentleCare",
        "GlassWater",
        "GrassShampoo",
        "GreatWhale",
        "GrownEarly",
        "HappyAcid",
        "HappyFisher",
        "HappyMemories",
        "HappyUnicorn",
        "HealthyWater",
        "HeavenPeach",
        "HeavyRain",
        "HiddenJaguar",
        "HighFlight",
        "ItmeoBranding",
        "JapanBlush",
        "JuicyCake",
        "JuicyPeach",
        "JungleDay",
        "KindSteel",
        "LadogaBottom",
        "LadyLips",
        "LandingAircraft",
        "LeCocktail",
        "LemonGate",
        "LightBlue",
        "LilyMeadow",
        "LoveKiss",
        "MagicLake",
        "MagicRay",
        "MalibuBeach",
        "MarbleWall",
        "MarsParty",
        "MeanFruit",
        "MidnightBloom",
        "MillenniumPine",
        "MindCrawl",
        "MixedHopes",
        "MoleHall",
        "MorningSalad",
        "MorpheusDen",
        "MountainRock",
        "NearMoon",
        "Nega",
        "NewLife",
        "NewRetrowave",
        "NewYork",
        "NightCall",
        "NightFade",
        "NightParty",
        "NightSky",
        "NorseBeauty",
        "NorthMiracle",
        "OctoberSilence",
        "OldHat",
        "OrangeJuice",
        "OverSun",
        "PaloAlto",
        "PartyBliss",
        "PassionateBed",
        "PerfectBlue",
        "PerfectWhite",
        "PhoenixStart",
        "PlumBath",
        "PlumPlate",
        "PoliteRumors",
        "PremiumDark",
        "PremiumWhite",
        "PurpleDivision",
        "RainyAshville",
        "RareWind",
        "RedSalvation",
        "RichMetal",
        "RipeMalinka",
        "RiskyConcrete",
        "RiverCity",
        "RoyalGarden",
        "SaintPetersburg",
        "SaltMountain",
        "SandStrike",
        "SeaLord",
        "SeaStrike",
        "Seashore",
        "ShadyWater",
        "SharpBlues",
        "SharpeyeEagle",
        "ShyRainbow",
        "SkyGlider",
        "SleeplessNight",
        "SmartIndigo",
        "SmilingRain",
        "SnowAgain",
        "SoftCherish",
        "SoftGrass",
        "SoftLipstick",
        "SolidStone",
        "SpaceShift",
        "SpikyNaga",
        "SpringWarmth",
        "StarWine",
        "StrictNovember",
        "StrongBliss",
        "StrongStick",
        "SugarLollipop",
        "SummerGames",
        "SunVeggie",
        "SunnyMorning",
        "SupremeSky",
        "SweetDessert",
        "SweetPeriod",
        "TeenNotebook",
        "TeenParty",
        "TemptingAzure",
        "TrueSunset",
        "ViciousStance",
        "WarmFlame",
        "WideMatrix",
        "WildApple",
        "WinterNeva",
        "WitchDance",
        "YoungGrass",
        "YoungPassion",
        "ZeusMiracle"
    };

    static inline const std::vector<QGradient::Preset> presets = {
        QGradient::AboveTheSky,
        QGradient::AfricanField,
        QGradient::AlchemistLab,
        QGradient::AmourAmour,
        QGradient::AmyCrisp,
        QGradient::AngelCare,
        QGradient::AquaGuidance,
        QGradient::AquaSplash,
        QGradient::AwesomePine,
        QGradient::BigMango,
        QGradient::BlackSea,
        QGradient::Blessing,
        QGradient::BurningSpring,
        QGradient::CheerfulCaramel,
        QGradient::ChildCare,
        QGradient::CleanMirror,
        QGradient::CloudyApple,
        QGradient::CloudyKnoxville,
        QGradient::CochitiLake,
        QGradient::ColdEvening,
        QGradient::ColorfulPeach,
        QGradient::ConfidentCloud,
        QGradient::CrystalRiver,
        QGradient::Crystalline,
        QGradient::DeepBlue,
        QGradient::DeepRelief,
        QGradient::DenseWater,
        QGradient::DesertHump,
        QGradient::DirtyBeauty,
        QGradient::DustyGrass,
        QGradient::EternalConstance,
        QGradient::EverlastingSky,
        QGradient::FabledSunset,
        QGradient::FarawayRiver,
        QGradient::FebruaryInk,
        QGradient::FlyHigh,
        QGradient::FlyingLemon,
        QGradient::ForestInei,
        QGradient::FreshMilk,
        QGradient::FreshOasis,
        QGradient::FrozenBerry,
        QGradient::FrozenDreams,
        QGradient::FrozenHeat,
        QGradient::FruitBlend,
        QGradient::GagarinView,
        QGradient::GentleCare,
        QGradient::GlassWater,
        QGradient::GrassShampoo,
        QGradient::GreatWhale,
        QGradient::GrownEarly,
        QGradient::HappyAcid,
        QGradient::HappyFisher,
        QGradient::HappyMemories,
        QGradient::HappyUnicorn,
        QGradient::HealthyWater,
        QGradient::HeavenPeach,
        QGradient::HeavyRain,
        QGradient::HiddenJaguar,
        QGradient::HighFlight,
        QGradient::ItmeoBranding,
        QGradient::JapanBlush,
        QGradient::JuicyCake,
        QGradient::JuicyPeach,
        QGradient::JungleDay,
        QGradient::KindSteel,
        QGradient::LadogaBottom,
        QGradient::LadyLips,
        QGradient::LandingAircraft,
        QGradient::LeCocktail,
        QGradient::LemonGate,
        QGradient::LightBlue,
        QGradient::LilyMeadow,
        QGradient::LoveKiss,
        QGradient::MagicLake,
        QGradient::MagicRay,
        QGradient::MalibuBeach,
        QGradient::MarbleWall,
        QGradient::MarsParty,
        QGradient::MeanFruit,
        QGradient::MidnightBloom,
        QGradient::MillenniumPine,
        QGradient::MindCrawl,
        QGradient::MixedHopes,
        QGradient::MoleHall,
        QGradient::MorningSalad,
        QGradient::MorpheusDen,
        QGradient::MountainRock,
        QGradient::NearMoon,
        QGradient::Nega,
        QGradient::NewLife,
        QGradient::NewRetrowave,
        QGradient::NewYork,
        QGradient::NightCall,
        QGradient::NightFade,
        QGradient::NightParty,
        QGradient::NightSky,
        QGradient::NorseBeauty,
        QGradient::NorthMiracle,
        QGradient::OctoberSilence,
        QGradient::OldHat,
        QGradient::OrangeJuice,
        QGradient::OverSun,
        QGradient::PaloAlto,
        QGradient::PartyBliss,
        QGradient::PassionateBed,
        QGradient::PerfectBlue,
        QGradient::PerfectWhite,
        QGradient::PhoenixStart,
        QGradient::PlumBath,
        QGradient::PlumPlate,
        QGradient::PoliteRumors,
        QGradient::PremiumDark,
        QGradient::PremiumWhite,
        QGradient::PurpleDivision,
        QGradient::RainyAshville,
        QGradient::RareWind,
        QGradient::RedSalvation,
        QGradient::RichMetal,
        QGradient::RipeMalinka,
        QGradient::RiskyConcrete,
        QGradient::RiverCity,
        QGradient::RoyalGarden,
        QGradient::SaintPetersburg,
        QGradient::SaltMountain,
        QGradient::SandStrike,
        QGradient::SeaLord,
        QGradient::SeaStrike,
        QGradient::Seashore,
        QGradient::ShadyWater,
        QGradient::SharpBlues,
        QGradient::SharpeyeEagle,
        QGradient::ShyRainbow,
        QGradient::SkyGlider,
        QGradient::SleeplessNight,
        QGradient::SmartIndigo,
        QGradient::SmilingRain,
        QGradient::SnowAgain,
        QGradient::SoftCherish,
        QGradient::SoftGrass,
        QGradient::SoftLipstick,
        QGradient::SolidStone,
        QGradient::SpaceShift,
        QGradient::SpikyNaga,
        QGradient::SpringWarmth,
        QGradient::StarWine,
        QGradient::StrictNovember,
        QGradient::StrongBliss,
        QGradient::StrongStick,
        QGradient::SugarLollipop,
        QGradient::SummerGames,
        QGradient::SunVeggie,
        QGradient::SunnyMorning,
        QGradient::SupremeSky,
        QGradient::SweetDessert,
        QGradient::SweetPeriod,
        QGradient::TeenNotebook,
        QGradient::TeenParty,
        QGradient::TemptingAzure,
        QGradient::TrueSunset,
        QGradient::ViciousStance,
        QGradient::WarmFlame,
        QGradient::WideMatrix,
        QGradient::WildApple,
        QGradient::WinterNeva,
        QGradient::WitchDance,
        QGradient::YoungGrass,
        QGradient::YoungPassion,
        QGradient::ZeusMiracle
    };

};

#endif // BACKGROUNDAPPLIER_H
